batch_size: 256
experiment_name: test_disfa
root: ~
train: ~
val: ~
test: ~
gpu_ids: '0'
dataset: 'DISFA'
start_epochs: 0
neg_alpha: 1.6
pose_alpha: 0.1
wd: 1.0e-4
T: 0.07
S: 3
C: 16
num_threads: 3
save_epoch: 100
dim: 512
linear_dim: 12288
checkpoint_dir: ./checkpoints
epochs: 6000
continue_train: False
eval: True
eval_mode: 'exp'
eval_threads: 0.5
eval_epochs: 30
seed: 3456
log_path: ./logs
model_name: exppose
dataset_name: audetectiondb
img_size: 64
lr: 1.0e-4
print_img: 50
print_loss : 20
load_model: ~
save_img_dir: ./save_img
save_img: False
print_network: False
classes_num: 8
linear_lr: 1.0e-3
warm_up: -1